app:
  env: dev
server:
  port: 8020
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://e.coding.net/bucket-z/spring-cloud-demo/config-repo.git
          username: ${username}
          password: ${password}
          basedir: /home/zhou/workspaces/spring-cloud-demo/config/repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
