version: "2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: my_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
        # server port
      - "5672:5672"
    #   management page port
      - "15672:15672"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # hostname: my_rabbitmq
    # environment:
    #   RABBITMQ_DEFAULT_USER: admin
    #   RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "9411:9411"
