version: "2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    hostname: my_rabbitmq
    ports:
        # server port
      - "5672:5672"
    #   management page port
      - "15672:15672"

