app:
  env: dev
server:
  port: 8000
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?useUnicode=true&characterEncoding=utf8
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

